### ISSUE TITLE
Move to STL Containers

### ISSUE THREAD

**Issue by JWhitleyWork** [astuff/network_interface#14]
`network_interface` currently uses mostly C-style arrays. This should be updated to use STL containers like vector or deque.

**Comment by JWhitleyAStuff** [comment]
@rgunjala93 - Can you please test the branch maint/return_vectors with the following repos/branches:

- ibeo_core : maint/updates_to_network_interface
- ibeo_lux : maint/updates_to_network_interface

We need validation that this new method will work and it will allow us to make the required updates to `ibeo_lux` and `ibeo_scala`.

**Comment by JWhitleyWork** [comment]
Closed by #25.
